---
id: Kolab_FreeBusy
name: Kolab_FreeBusy
full: Kolab application providing free/busy information
description: >-
  Free/busy information for the users of a Kolab server. A Kolab client changing
  calendar data in an IMAP folder is required to call the triggering script
  provided within this package via HTTP. This will refresh the cache maintained
  by this package with partial free/busy data. This partial data sets are
  finally combined to the complete free/busy information once a client requests
  this data for a particular user.
list: dev
type: library
authors:
  -
    name: Gunnar Wrobel
    user: wrobel
    email: p@rdus.de
    active: true
    role: lead
version:
  release: 1.0.0alpha1
  api: 1.0.0
state:
  release: beta
  api: beta
license:
  identifier: LGPL-2.1-only
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      horde/kolab_format: ^3
      horde/kolab_server: ^3
      horde/kolab_storage: ^3
      horde/icalendar: ^3
      horde/date: ^3
      horde/translation: ^3
      horde/util: ^3
  optional:
    composer:
      horde/test: ^3
  dev:
    composer:
      horde/test: ^3
